config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  root "home#index"
  resources:categories
  default_url_options :host => "example.com"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }

  get  "/home/user", to:  "home#user"
  get  "/home/admin", to:  "home#admin"
  get  "/users/sign_out", to:  "users/sessions#destroy"

  get  "/users/block", to:  "users#block"
  get  "/users/unblock", to:  "users#unblock"

  get  "/products/index", to:  "products#index"
  get  "/products/sell", to:  "products#sell"
  get  "/search", to:  "products#search"
  get  "/search_category", to:  "products#search_category"

  get  "/products/myproduct", to:  "products#myproduct"
  get  "/products/:id", to: "products#show"
  get  "/product/accept", to:  "products#accept"
  get  "/product/reject", to:  "products#reject"
  get  "/product/offeraccept", to:  "products#offeraccept"

  get  "/product/productname", to:  "products#productname"
  get  "/product/pending", to:  "products#pending"
  get  "/product/offer", to:  "products#offer"
  get  "/product/proposal", to:  "products#proposal"
  get  "/view", to:  "proposals#view"





  resources:products, only:[:new , :create , :destroy, :edit , :update] 

  resources :users do
    resources:products
  end

  resources :prodcut do
    member do
      resource:proposals, only:[:new, :create, :edit, :update] 
      get  "/proposals", to:  "proposals#index"

    end
  end

  resource:contact
  end

app/models/user.rb
class User < ApplicationRecord
  has_many :products
  # Include default devise modules. Others available are:
  # , :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable, :confirmable
end

app/controllers/users/confirmations_controller.rb
# frozen_string_literal: true

class Users::ConfirmationsController < Devise::ConfirmationsController
  # GET /resource/confirmation/new
  # def new
  #   super
  # end

  # POST /resource/confirmation
  # def create
  #   super
  # end

  # GET /resource/confirmation?confirmation_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after resending confirmation instructions.
  # def after_resending_confirmation_instructions_path_for(resource_name)
  #   super(resource_name)
  # end

  # The path used after confirmation.
  # def after_confirmation_path_for(resource_name, resource)
  #   super(resource_name, resource)
  # end
end

app/controllers/users/omniauth_callbacks_controller.rb
# frozen_string_literal: true

class Users::OmniauthCallbacksController < Devise::OmniauthCallbacksController
  # You should configure your model like this:
  # devise :omniauthable, omniauth_providers: [:twitter]

  # You should also create an action method in this controller like this:
  # def twitter
  # end

  # More info at:
  # https://github.com/heartcombo/devise#omniauth

  # GET|POST /resource/auth/twitter
  # def passthru
  #   super
  # end

  # GET|POST /users/auth/twitter/callback
  # def failure
  #   super
  # end

  # protected

  # The path used when OmniAuth fails
  # def after_omniauth_failure_path_for(scope)
  #   super(scope)
  # end
end

app/controllers/users/passwords_controller.rb
# frozen_string_literal: true

class Users::PasswordsController < Devise::PasswordsController
  # GET /resource/password/new
  # def new
  #   super
  # end

  # POST /resource/password
  # def create
  #   super
  # end

  # GET /resource/password/edit?reset_password_token=abcdef
  # def edit
  #   super
  # end

  # PUT /resource/password
  # def update
  #   super
  # end

  # protected

  # def after_resetting_password_path_for(resource)
  #   super(resource)
  # end

  # The path used after sending reset password instructions
  # def after_sending_reset_password_instructions_path_for(resource_name)
  #   super(resource_name)
  # end
end

app/controllers/users/registrations_controller.rb
# frozen_string_literal: true

class Users::RegistrationsController < Devise::RegistrationsController
  # before_action :configure_sign_up_params, only: [:create]
  # before_action :configure_account_update_params, only: [:update]

  # GET /resource/sign_up
  # def new
  #   super
  # end

  # POST /resource
  # def create
  #   super
  # end

  # GET /resource/edit
  # def edit
  #   super
  # end

  # PUT /resource
  # def update
  #   super
  # end

  # DELETE /resource
  # def destroy
  #   super
  # end

  # GET /resource/cancel
  # Forces the session data which is usually expired after sign
  # in to be expired now. This is useful if the user wants to
  # cancel oauth signing in/up in the middle of the process,
  # removing all OAuth session data.
  # def cancel
  #   super
  # end

  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_up_params
  #   devise_parameter_sanitizer.permit(:sign_up, keys: [:attribute])
  # end

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_account_update_params
  #   devise_parameter_sanitizer.permit(:account_update, keys: [:attribute])
  # end

  # The path used after sign up.
  # def after_sign_up_path_for(resource)
  #   super(resource)
  # end

  # The path used after sign up for inactive accounts.
  # def after_inactive_sign_up_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users/sessions_controller.rb
# frozen_string_literal: true

class Users::SessionsController < Devise::SessionsController
  # before_action :configure_sign_in_params, only: [:create]
    before_action :check_for_blocking
  # GET /resource/sign_in
  # def new
  #   super
  # end

  # POST /resource/sign_in
  # def create
  #   super
  # end

  # DELETE /resource/sign_out
  # def destroy
  #   super
  # end

  def check_for_blocking
    if current_user.present?
      if current_user.status=="blocked"
        sign_out current_user
        redirect_to  new_user_session_path, :notice => "This account has been Blocked - Please Contact Admin"
      end
  end
  
  end
  # protected

  # If you have extra params to permit, append them to the sanitizer.
  # def configure_sign_in_params
  #   devise_parameter_sanitizer.permit(:sign_in, keys: [:attribute])
  # end
end

app/controllers/users/unlocks_controller.rb
# frozen_string_literal: true

class Users::UnlocksController < Devise::UnlocksController
  # GET /resource/unlock/new
  # def new
  #   super
  # end

  # POST /resource/unlock
  # def create
  #   super
  # end

  # GET /resource/unlock?unlock_token=abcdef
  # def show
  #   super
  # end

  # protected

  # The path used after sending unlock password instructions
  # def after_sending_unlock_instructions_path_for(resource)
  #   super(resource)
  # end

  # The path used after unlocking the resource
  # def after_unlock_path_for(resource)
  #   super(resource)
  # end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_action :authenticate_user!

  def index
    @user = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
  end

  def update 
    @user = User.find(params[:id])

    if @user.update(user_params)
      redirect_to @user
    else
      render :edit
    end
  end
  
  def block
    @user = User.find(params[:user_id])
    if @user.update(status:"blocked")
      redirect_to @user
    end
  end


  def unblock
    @user = User.find(params[:user_id])
    if @user.update(status:"unblock")
      redirect_to @user
    end
  end
  



  private 
  
  def user_params
    params.require(:user).permit(:name, :email, :mobile)    
  end
end

app/views/users/edit.html.erb
<section class="h-100% gradient-form" style="background-color: #07a">
<div class="container py-5 h-100%">
  <div class="row d-flex justify-content-center align-items-center h-100">
    <div class="col-xl-5">
      <div class="card rounded-3 text-black">
            <div class="card-body p-md-5 mx-md-4">
              <div class="text-center">
                <img src="https://mdbcdn.b-cdn.net/img/Photos/new-templates/bootstrap-login-form/lotus.webp"
                  style="width: 185px;" alt="logo">
                <h4 class="mt-1 mb-5 pb-1">We are The Lotus Team</h4>
              </div>
                <p>Please edit your account</p>
                <%= form_with model: @user do |f| %>
                   <div class="field m-2">
                    <%= f.label :name %><br />
                    <%= f.text_field :name, autofocus: true, autocomplete: "name",placeholder: 'name' %>
                  </div>


                  <div class="form-group clearfix m-2">
                    <%= f.label :mobile %><br />
                    <%= f.text_field :mobile, autofocus: true, autocomplete: "mobile",placeholder: 'mobile'  %>
                  </div>

                  <div class="field m-2">
                    <%= f.label :email %><br />
                    <%= f.email_field :email, autofocus: true, autocomplete: "email",placeholder: 'email' %>
                  </div>

                <div  class="text-center pt-1 mb-3 pb-1 m-2">
                    <%= f.submit  %>
                </div>
                <% end %>
                
                <div  class="text-center pt-1 mb-3 pb-1 m-2">
                    <a href="<%= edit_user_registration_path(current_user) %>">edit your password</a>
                </div>

        </div>
      </div>
    </div>
  </div>
</div>
</section>

app/views/users/index.html.erb
<h1>Users</h1>

<ul>
  <% @user.each do |user| %>
    <li>
      <%=link_to  user.name, user %>
    </li>
  <% end %>
</ul>

app/views/users/show.html.erb
<h1>Name:- <%= @user.name %></h1>

<p>Email:- <%= @user.email %></p>
<p>Mobile:- <%= @user.mobile %></p>
<p>This user will <span style="background-color:#FF0000"><%= @user.status %></span></p> 
<p><%= link_to "Edit Details" , edit_user_path(current_user)%></p>

<% if current_user.role=="Admin"%>
  <p><%= link_to "Block User" , users_block_path(user_id: @user.id)%></p>
  <p><%= link_to "UnBlock User" , users_unblock_path(user_id: @user.id)%></p>
<% end %>