config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  root "home#index"
  resources:categories
  default_url_options :host => "example.com"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }

  get  "/home/user", to:  "home#user"
  get  "/home/admin", to:  "home#admin"
  get  "/users/sign_out", to:  "users/sessions#destroy"

  get  "/users/block", to:  "users#block"
  get  "/users/unblock", to:  "users#unblock"

  get  "/products/index", to:  "products#index"
  get  "/products/sell", to:  "products#sell"
  get  "/search", to:  "products#search"
  get  "/search_category", to:  "products#search_category"

  get  "/products/myproduct", to:  "products#myproduct"
  get  "/products/:id", to: "products#show"
  get  "/product/accept", to:  "products#accept"
  get  "/product/reject", to:  "products#reject"
  get  "/product/offeraccept", to:  "products#offeraccept"

  get  "/product/productname", to:  "products#productname"
  get  "/product/pending", to:  "products#pending"
  get  "/product/offer", to:  "products#offer"
  get  "/product/proposal", to:  "products#proposal"
  get  "/view", to:  "proposals#view"





  resources:products, only:[:new , :create , :destroy, :edit , :update] 

  resources :users do
    resources:products
  end

  resources :prodcut do
    member do
      resource:proposals, only:[:new, :create, :edit, :update] 
      get  "/proposals", to:  "proposals#index"

    end
  end

  resource:contact
  end

app/views/shared/_alert.html.erb
 <% if notice %>
    <p class="alert alert-primary" role="alert"><%= notice %></p>
<% end %>
 <% if alert %>
    <p class="alert alert-danger" role="alert"><%= alert %></p>
<% end %>

app/views/shared/_header.html.erb
<section class="border  align-items-center flex-column">
<nav class="navbar navbar-expand-lg navbar-dark bg-secondary">
  <div class="container-fluid justify-content-between ">
    <div class="collapse navbar-collapse" id="navbarSupportedContent" >
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="<%=products_index_path%>">Home</a>
        </li>  
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="/products/sell">+Sell</a>
        </li>
        <%= form_tag(search_path, :method => "get") do %>
          <div class="input-group">
              <%= search_field_tag :search, params[:search], placeholder:"Type", class: "form-control" %>
              <div class="input-group-btn">
                  <%= button_tag "Search", :class => "btn btn-info glyphicon-search", :name => nil %>
              </div>
          </div>
        <% end %>

        <div>

      </ul>

    </div>

    <div class="dropdown">
        <% if current_user.present? %>
          <a class="btn btn-success dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">
            <%= current_user.name[0,1]%></a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">  
            <li><a class="dropdown-item " href=""><%=current_user.name %></a></li>
            <li><a class="dropdown-item " href="<%=user_path(current_user) %>">view profile</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%=edit_user_path(current_user) %>">edit your profile</a></li>
            <a class="dropdown-item" class="icon" href="/users/sign_out"><span class="glyphicon glyphicon-log-out"></span>sign-out </a>
          </ul>
        <% end %>
    </div>

      <% if current_user.present? %>
        <div class="dropdown p-2">
          <% if current_user.role!= "User"%>
            <a class="btn btn-info dropdown-toggle" href="#" role="button" id="dropdownMenuLink" data-bs-toggle="dropdown" aria-expanded="false">Admin</a>
          <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">  
            <li><a class="dropdown-item " href="<%=users_path %>">Users</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%=product_productname_path %>">Products</a></li>
            <li><hr class="dropdown-divider"></li>
            <li><a class="dropdown-item" href="<%=categories_path %>">Categories</a></li>
          </ul>
          <% end %>
       </div>
      <% end %>

    </div>
  </div>
  </div>
</nav>
</section>

app/views/shared/_pagination.html.erb
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%= paginate @product %>
  </ul>
</nav>