config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  root "home#index"
  resources:categories
  default_url_options :host => "example.com"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }

  get  "/home/user", to:  "home#user"
  get  "/home/admin", to:  "home#admin"
  get  "/users/sign_out", to:  "users/sessions#destroy"

  get  "/users/block", to:  "users#block"
  get  "/users/unblock", to:  "users#unblock"

  get  "/products/index", to:  "products#index"
  get  "/products/sell", to:  "products#sell"
  get  "/search", to:  "products#search"
  get  "/search_category", to:  "products#search_category"

  get  "/products/myproduct", to:  "products#myproduct"
  get  "/products/:id", to: "products#show"
  get  "/product/accept", to:  "products#accept"
  get  "/product/reject", to:  "products#reject"
  get  "/product/offeraccept", to:  "products#offeraccept"

  get  "/product/productname", to:  "products#productname"
  get  "/product/pending", to:  "products#pending"
  get  "/product/offer", to:  "products#offer"
  get  "/product/proposal", to:  "products#proposal"
  get  "/view", to:  "proposals#view"





  resources:products, only:[:new , :create , :destroy, :edit , :update] 

  resources :users do
    resources:products
  end

  resources :prodcut do
    member do
      resource:proposals, only:[:new, :create, :edit, :update] 
      get  "/proposals", to:  "proposals#index"

    end
  end

  resource:contact
  end

app/models/category.rb
class Category < ApplicationRecord
    has_many :products
    validates :category_name, presence: true,uniqueness: true
end

app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  def index
    @category = Category.all
  end

  def show
    @category = Category.find(params[:id])
  end

  def new
    @category = Category.new
  end

  def create
    @category = Category.new(category_parmas)
    if @category.save
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end  
  end


  def edit
    @category = Category.find(params[:id])
  end

  def update
    @category =Category.find(params[:id])
    if @category.update(category_parmas)
      redirect_to categories_path
    else
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    @category =Category.find(params[:id])
    @category.destroy
    redirect_to categories_path
  end

  private
   def category_parmas
    params.require(:category).permit(:category_name)
   end
end

app/views/categories/edit.html.erb
<h1>Edit Category</h1>

<%= form_for @category do |form| %>
    <div>
      <%= form.label :category_name %><br>
      <%= form.text_field :category_name %>
    </div>
  


    <div>
      <%= form.submit "submit" %>
    </div>

  <% end %>

app/views/categories/index.html.erb
<h1> All Categories </h1>


<ul>
  <% @category.each do |category| %>
    <li>
      <%=link_to  category.category_name, category %>
    </li>
  <% end %>
</ul>

<%= link_to "add new category" ,new_category_path%>

app/views/categories/new.html.erb
<h1>New Category</h1>

<%= form_for @category do |form| %>
    <div>
      <%= form.label :category_name %><br>
      <%= form.text_field :category_name %>
      <% @category.errors.full_messages_for(:category_name).each do |message| %>
      <div><%= message %></div>
      <% end %>
    </div>
  


    <div>
      <%= form.submit "submit" %>
    </div>

  <% end %>

app/views/categories/show.html.erb
<h1><%= @category.category_name %>  </h1>
<p><%= link_to "Destroy", category_path(@category.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p> 
<p><%= link_to "edit", edit_category_path(@category.id) %></p> 