config/routes.rb
Rails.application.routes.draw do
  get 'categories/index'

  root "home#index"
  resources:categories
  default_url_options :host => "example.com"
  devise_for :users, controllers: {
    sessions: 'users/sessions'
    }

  get  "/home/user", to:  "home#user"
  get  "/home/admin", to:  "home#admin"
  get  "/users/sign_out", to:  "users/sessions#destroy"

  get  "/users/block", to:  "users#block"
  get  "/users/unblock", to:  "users#unblock"

  get  "/products/index", to:  "products#index"
  get  "/products/sell", to:  "products#sell"
  get  "/search", to:  "products#search"
  get  "/search_category", to:  "products#search_category"

  get  "/products/myproduct", to:  "products#myproduct"
  get  "/products/:id", to: "products#show"
  get  "/product/accept", to:  "products#accept"
  get  "/product/reject", to:  "products#reject"
  get  "/product/offeraccept", to:  "products#offeraccept"

  get  "/product/productname", to:  "products#productname"
  get  "/product/pending", to:  "products#pending"
  get  "/product/offer", to:  "products#offer"
  get  "/product/proposal", to:  "products#proposal"
  get  "/view", to:  "proposals#view"





  resources:products, only:[:new , :create , :destroy, :edit , :update] 

  resources :users do
    resources:products
  end

  resources :prodcut do
    member do
      resource:proposals, only:[:new, :create, :edit, :update] 
      get  "/proposals", to:  "proposals#index"

    end
  end

  resource:contact
  end

app/models/product.rb
class Product < ApplicationRecord
  belongs_to :user
  belongs_to :category
  has_many :proposals
  has_one_attached :image
  paginates_per 20

  validates :name, presence: true
  validates :detail, presence: true
  validates :image, presence: true
  validates_numericality_of :price, only_numeric: true,presence: true


  def self.search(search)
    where("lower(product.name) LIKE :search ", search: "%#{search.downcase}%").uniq
  end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  before_action :authenticate_user!

    def index
      if params[:category].blank?
        @product = Product.where(status:"accepted").page(params[:page]).per(12)
      end
    end
    
    def productname
      @product = Product.all
    end
       
    def myproduct
      @product = current_user.products.page(params[:page]).per(12)
    end

    def search
      if params[:search].blank?
        redirect_to root_path and return
      else
        @product = Product.joins(:category).where("category_name LIKE ? OR lower(name) LIKE ?", "#{params[:search]}" , "%#{params[:search]}%").page(params[:page]).per(12) 
      end
    end

    def proposal
      @product = Product.find(params[:product_id])
        if(@product.user_id==current_user.id)
          @proposal = Proposal.where(product_id: params[:product_id])
        end
    end

    def show
        @product = Product.find(params[:id])
    end


    def new
      @product = Product.new(category_id: params[:category_id])
    end
    
    def create      
        @product =current_user.products.new(products_params)     
        if @product.save
          UserMailer.welcome(current_user,@product).deliver_now 
          redirect_to root_path
        else
          render :new, status: :unprocessable_entity
        end
    end

    def edit
      @product = Product.find(params[:id])
    end
  
    def update
      @product =current_user.products.find(params[:id])
  
      if @product.update(products_params)
        redirect_to root_path
      else
        render :new, status: :unprocessable_entity
      end
    end

    def destroy
      @product =current_user.products.find(params[:id])
      @product.destroy
      redirect_to root_path
    end

    def sell
      @category = Category.all
    end

    def detail
      @product = Product.find(params[:id])
    end
    
      
    def pending
      @product = Product.where(status: nil)
    end

    def accept
      @product = Product.where(status:"accepted")
      if params[:product_id].present?
        @product = Product.find(params[:product_id])
        if @product.update(status:"accepted")
          UserMailer.accept(current_user,@product).deliver_now 
          redirect_to @product
        end
      end
    end


    def reject
      @product = Product.where(status:"rejected")
      if params[:product_id].present?
        @product = Product.find(params[:product_id])
        if @product.update(status:"rejected")
          UserMailer.reject(current_user,@product).deliver_now 
          redirect_to @product
        end
      end
    end

    def offeraccept
      if params[:product_id].present?
        @product = Product.find(params[:product_id])
        if @product.update(price:params[:amount])
          redirect_to @product
        end
      end
    end




  private
    def products_params
      params.require(:product).permit(:name, :detail, :price , :image , :status, :category_id)
    end

end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for @product do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @product.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :detail %><br>
      <%= form.text_field :detail %>
      <% @product.errors.full_messages_for(:detail).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :price %><br>
      <%= form.text_field :price %>
      <% @product.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :image %><br>
      <%= form.file_field :image %>
      <% @product.errors.full_messages_for(:image).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 
   
    <div>
       <%= form.submit "submit" %>
    </div>

  <% end %>

app/views/products/accept.html.erb
<h1> Accept </h1>

<div class="row row-cols-1 row-cols-md-5 g-2  m-1 "> 


  <% @product.each do |product| %>
    <li>
      <%=link_to  product.name, product %>
    </li>
  <% end %>
</div>

app/views/products/detail.html.erb
<%= image_tag @product.image if @product.image.attached? %>

<h1><%= @product.name %></h1>
<p><%= @product.price %></p>
<p><%= @product.detail %></p>

app/views/products/edit.html.erb
<h1>Update Product</h1>

<%= render "form" , product: @product %>

app/views/products/index.html.erb
<div class="row row-cols-1 row-cols-md-4 g-2  m-1 "> 
    <% @product.each do |product| %>
          <div class="col-md-2">
            <div class="card h-100 ">
              <a href="<%=user_product_path(current_user, product)%>">
              <%= image_tag product.image, class: 'card-img-top', height: 150, width: 300 if product.image.attached?%>
              <div class="card-body">
                <p class="card-title"> <%= product.name %> </p>             
                <p class="card-text">₹ <%= product.price %></p>
              </div>
              </a>
            </div>
          </div>
    <% end %>
</div>
<br>
<nav aria-label="Page navigation example">
  <ul class="pagination justify-content-center">
    <%= paginate @product %>
  </ul>
</nav>

app/views/products/myproduct.html.erb
<h1> my product </h1>
  
<div class="row row-cols-1 row-cols-md-4 g-2  m-2 ">
    
 <% @product.each do |product| %>
    <div class="col-md-2">
      <div class="card h-100 ">
        <a href="<%=user_product_path(current_user, product)%>">
            <%= image_tag product.image, class: 'card-img-top', width: 300 if product.image.attached?%>
              <div class="card-body">

                <p class="card-title"> <%= product.name %> </p>
                <p class="card-text">₹ <%= product.price %></p>

              </div>
              </a>
            </div>

          </div>

      <% end %>
    </div>
  
  <%= render "shared/pagination" ,product: @product %>

  

app/views/products/new.html.erb
<h1>New Product</h1>

<%= form_for @product do |form| %>
    <div>
      <%= form.label :name %><br>
      <%= form.text_field :name %>
      <% @product.errors.full_messages_for(:name).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :detail %><br>
      <%= form.text_field :detail %>
      <% @product.errors.full_messages_for(:detail).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div>
  
    <div>
      <%= form.label :price %><br>
      <%= form.text_field :price %>
      <% @product.errors.full_messages_for(:price).each do |message| %>
        <div><%= message %></div>
      <% end %>      
    </div>
  
    <div>
      <%= form.label :image %><br>
      <%= form.file_field :image %>
      <% @product.errors.full_messages_for(:image).each do |message| %>
        <div><%= message %></div>
      <% end %>
    </div> 
    <div>
      <%= form.hidden_field :category_id %><br>
    </div> 



    <div>
      <%= form.submit "submit" %>
    </div>

  <% end %>

app/views/products/pending.html.erb
<h1> pending </h1>

<div class="row row-cols-1 row-cols-md-5 g-2  m-1 "> 


  <% @product.each do |product| %>
    <li>
      <%=link_to  product.name, product %>
    </li>
  <% end %>
</div>

app/views/products/productname.html.erb
<h1>Products</h1>
<p class="text-center p-1"><%= link_to "Pending" , product_pending_path,style: 'color:#FF0000;'%> 
  <%= link_to "Accept", product_accept_path ,style: 'color:#FF0000;'%>
  <%= link_to "Reject",product_reject_path ,style: 'color:#FF0000 ;' "m-5" %>
</p>

<div class="row row-cols-1 row-cols-md-5 g-2  m-1 "> 


  <% @product.each do |product| %>
    <li>
      <%=link_to  product.name, product %>
    </li>
  <% end %>
</div>

app/views/products/proposal.html.erb
<h1>Proposal on your Product</h1>

<ul>
  <% @proposal.each do |proposal| %>
    <li>
      <%=  proposal.amount %>
    </li>
  <% end %>
</ul>

app/views/products/reject.html.erb
<h1> reject </h1>

app/views/products/search.html.erb
<div class="row row-cols-1 row-cols-md-4 g-2  m-1 "> 
    <% @product.each do |product| %>
          <div class="col-md-2">
            <div class="card h-100 ">
              <a href="<%=user_product_path(current_user, product)%>">
              <%= image_tag product.image, class: 'card-img-top', height: 150, width: 300 if product.image.attached?%>
              <div class="card-body">
                <p class="card-title"> <%= product.name %> </p>             
                <p class="card-text">₹ <%= product.price %></p>
              </div>
              </a>
            </div>
          </div>
    <% end %>
</div>
<br>
<%= render "shared/pagination" ,product: @product %>

app/views/products/sell.html.erb
<p> Sell your Product </p>
<li> <%= link_to "My Product", products_myproduct_path(current_user.id) %> </li>
<table class="table w-25 table-bordered border-primary align-middle " >
  <thead>
    <tr>
      <th scope="col">Choose a category</th>
    </tr>
  </thead>
  <tbody>

    <tr>
      <td><%= link_to "Cars", new_user_product_path(current_user.id,category_id: 1) %></td>
    </tr>

    <tr>
      <td><%= link_to "Bikes", new_user_product_path(current_user.id,category_id: 2) %></td>
    </tr>

    <tr>
      <td><%= link_to "Mobile", new_user_product_path(current_user.id,category_id: 3) %></td>
    </tr>

    <tr>  
      <td><%= link_to "Properties", new_user_product_path(current_user.id,category_id: 4) %></td>
    </tr>

    <tr>
      <td><%= link_to "Electronic", new_user_product_path(current_user.id,category_id: 5) %></td>
    </tr>

    <tr>      
      <td><%= link_to "Furniture", new_user_product_path(current_user.id,category_id: 6) %></td>
    </tr>

  </tbody>
</table>

app/views/products/show.html.erb
    <%= image_tag @product.image ,width: 400 if @product.image.attached? %>
    <p><%= @product.name %></p>
    <h1>₹ <%= @product.price %></h1>
    <% if current_user.id !=@product.user_id %>
    <div class="d-grid gap-1 col-2 m-">
        <%= link_to "Make a Offer", new_proposals_path(product_id: @product.id) %>
    <td><%= link_to "view your offer", view_path(product_id: @product.id) %></td>

    </div>
    <% end %>
    <p><%= @product.detail %></p>  
  
    <% if current_user.role=="Admin" || current_user.id ==@product.user_id %>    
        <p> <%= link_to "Edit", edit_user_product_path(current_user, @product.id) %></p>
        <p><%= link_to "Destroy", user_product_path(current_user, @product.id), data:{turbo_method: :delete, turbo_confirm: "Are you sure?"} %></p> 
    <% end %>

    <% if current_user.role=="Admin" %>    
        <p><%= link_to "Accept Product" , product_accept_path(product_id: @product.id)%></p>
        <p><%= link_to "Reject Product" , product_reject_path(product_id: @product.id)%></p>
    <% end %>
 
    


   <% if current_user.id==@product.user_id %>    
      <td><%= link_to "offers", proposals_prodcut_path(product_id: @product.id) %></td>
    <% end %>